language: node_js
node_js: lts/*
install:
  - cd backend
  - npm install
  - cd ..
  - cd client
  - npm install
  - cd ..
script:
  - cd backend
  - sha512sum node_modules/rxjs/Observable.js
  - npm run dist:all
  - cd ..
